version: '3'

services:
  db:
    image: postgres:12.4
    volumes:
      - ./schema:/docker-entrypoint-initdb.d:ro
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432
